# -*- coding: utf-8 -*-
"""William Li - Assignment 7 Python Dictionaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXPH8qvKHTjyrg6ASCqAQiU0fXjtUarP

# Python Assignment 7 - Dictionaries

## Question 1 (10 pts)
Write a **loop** to construct a dictionary where the keys are numbers between 1 and 15 (both included) and the values are square of keys.

Your output should look like this:
`{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}`
"""

# Construct your dictionary here
# Write a loop to accomplish this
dictionary ={};
for i in range(1,15,1):
  dictionary[i]=i*i;

# You don't have to do anything here
# Just run the cell
# print your dictionary

print(dictionary)



"""## Question 2 (10 pts)

Write a Python script to concatenate following dictionaries to create a new one.

Sample Dictionary:

`dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50, 6:60}`

Expected Result:

`{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}`

**Your Method Should Work for All Dictionaries**
"""

# Sample Dictionaries:

dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50, 6:60}

# Construct your dictionary here
dictionary = {};
for key in dic1:
  dictionary[key]=dic1[key];
for key in dic2:
  dictionary[key]=dic2[key];
for key in dic3:
  dictionary[key]=dic3[key];

# You don't have to do anything here
# Just run the cell
# print your dictionary

print(dictionary)

"""## Question 3 (10 pts)
In this problem you are given two lists: `store_list` records the places at which you spent your credit card. `amount_list` stores the amount you spent. These two lists are of same length and the same index refers to the same purchase.

Write a program to print to the screen the total amount that was purchased at each store on the
bill. Your output should look like this

`
Shake Shack: $16
Grocery Hut: $293
Ace Hardware: $14
Joan's Fabric: $18
Nom Nom Nom: $12
`

**Hint: using dictionaries would be a really good way to solve this problem!**
"""

# Run this cell first, but do not change anything
store_list = ['Shake Shack', 'Grocery Hut', 'Grocery Hut', 'Ace Hardware', 'Grocery Hut',
              "Joan's Fabric", 'Nom Nom Nom',  'Grocery Hut', 'Shake Shack']
amount_list = [9, 82, 117, 14, 65, 18, 12, 29, 7]

# Write your code for Question 3 here
dic={};
for i in range(len(store_list)):
  if(dic.get(store_list[i])!=None):
    dic[store_list[i]]+=amount_list[i];
  else:
    dic[store_list[i]]=amount_list[i];

# Print Your Result here
print(dic);