# -*- coding: utf-8 -*-
"""William Li - G10 2021 Fall Homework 3 - Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/143g4EZgkzBeotdcCdPqnm1Buy0yIRmb9

# G10 2021 Fall Homework 3 - Functions (40 pts)


---

## Question 1 (10 pts)
Write a function that **returns** the Max of three numbers

1.   Complete the code for the function in the 1st cell. (Don't forget to run the cell before testing in 2nd cell)
2.   Run the 2nd cell to test your function. And you should get:

```
>>>print(max_three_numbers(1, 2, 3))
3
>>>print(max_three_numbers(1, 3, 2))
3
>>>print(max_three_numbers(3, 2, 1))
3
```
"""

# Define the function here, it has three inputs
def max_three_numbers(a, b, c):
  return max(max(a,b),c);

# DON'T CHANGE ANYTHING HERE
# Just run the cell to test your function

print(max_three_numbers(1, 2, 3))
print(max_three_numbers(1, 3, 2))
print(max_three_numbers(3, 2, 1))

"""## Question 2 (10 pts)
* Define a function called `factorial()`, that takes as input a non-negative integer and **returns** its factorial

$$n! = n*(n-1)*\cdots*1$$
* Notice that

$$0! = 1$$

* Then print the factorials from 0, 1, ... to 10
    * Your output should look like this:
    ```
    0, 1
    1, 1
    2, 2
    ...
    10, 3628800
    ```

"""

# Define the function of factorial here

def factorial(n):
  if(not n): return 1;
  else: return n*factorial(n-1);

# Print the factorials from 0, 1, ... to 10


for i in range (0,11,1):
  print(factorial(i));

"""## Question 3 (10 pts)
Write a Python function to check whether a number is perfect or not.
* According to Wikipedia : In number theory, a perfect number is a positive integer that is equal to the sum of its proper positive divisors, that is, the sum of its positive divisors excluding the number itself (also known as its aliquot sum). Equivalently, a perfect number is a number that is half the sum of all of its positive divisors (including itself).
* Example : The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6. Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6. The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.
"""

# Define the function here
def isperfect(n):
  denominators=[];tmp=0;
  for i in range(1,n,1):
    if(not n%i): denominators.append(i);
  for i in range(0,len(denominators),1):tmp+=denominators[i];
  if(not tmp-n): print("Y");
  else: print("N");

# Test your function here
isperfect(8128);

"""## Question 4 - Finding factors (10 pts)

Implement a function that **prints** out all the factors of the given number (you can assume the input is an integer but not neccesarily positive), one by one. Your function should check that the en|tered number is greater than 0. 

1.   Complete the code for the function in the 1st cell. (Don't forget to run the cell before testing in 2nd cell)
2.   Run the 2nd cell to test your function. And you should get:

```
>>> f(42)
1
2
3
6
7
14
21
42
>>> f(53)
1
53
>>> f(0)
Input should be a positive integer, please try again.
```
"""

# Write your code here for Question 2.2
# Define the function here, it has 1 input
def f(n):
  if(n<=0): print("Input should be a positive integer, please try again.");return;
  for i in range(1,n,1):
    if(not n%i): print(i);
  print(n);

# DON'T CHANGE ANYTHING HERE
# Just run the cell to test your function

f(42)
f(53)
f(0)

"""## (Optional) Question 5 - (Bonus 10 pts)
Write a Python function that **prints** out the first n rows of Pascal's triangle.
* Sample Pascal's triangle :
![image.png](https://i.loli.net/2020/07/22/bQ92VpZrlkSFasL.png)
* Each number is the two numbers above it added together

**NOTE:** This question is for those who would like some more challenges. Points will be added to the total grade until maximum amount of points are reached. (Maximum grade you can obtain for this assignment is 40) 
"""

# Define the function here
def solvepascaltriangle(n):
  triangle=[[0 for i in range(99)] for j in range(99)];
  for i in range(1,n+1,1):
    for j in range(1,i+1,1):
      if(i==1 or j==1 or j==i):triangle[i][j]=1;
      else:triangle[i][j]=(triangle[i-1][j-1]+triangle[i-1][j]);
  for i in range(1,n+1,1):
    for j in range(0,int((2*n-1-(2*i-1))/2),1):print(" ",end="");
    for j in range(1,i+1,1):print(triangle[i][j],end=" ");
    print("\n");

# Test your function here
solvepascaltriangle(5);