# -*- coding: utf-8 -*-
"""William Li - G10 2021 Fall Homework 4 - Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zdmcgKr4Mv1YKOyhz-dn62xDRvYTu828

# G10 2021 Fall Homework 4 - Lists (35 pts)


---

## Question 1 - “Sandcastle” (warm-up) problem (10 pts)
You should write a function called `greater_than_10` that
is passed a list of integers and returns a new list which contains only the numbers greater
than 10 from the original list passed in. For example, if your function was called as follows:

`greater_than_10([20, 6, 12, -3, 14])`

then it should return the new list:

`[20, 12, 14]`

If your function is called with the empty list (or a list that does not contain any values
greater than 10), as follows:

`greater_than_10([])`

then it should return a new empty list:

`[]`
"""

# Define the function greater_than_10 here

def greater_than_10(num_list):
    """
    This function is passed a list of integers (num_list) and should
    return a list containing only those numbers from num_list that
    have a value greater than 10.
    """
    new_list=[];
    for i in range(len(num_list)):
      if(num_list[i]>10):
        new_list.append(num_list[i]);
    return new_list;

# Test your function here
# Don't change anything here

list1 = [20, 6, 12, -3, 14]
result_list = greater_than_10(list1)
print(result_list)      # should print [20, 12, 14]

list2 = [16]
result_list = greater_than_10(list2)
print(result_list)      # should print [16]

list3 = [1, 2, 3, 4]
result_list = greater_than_10(list3)
print(result_list)      # should print []

list4 = []
result_list = greater_than_10(list4)
print(result_list)      # should print []

"""## Question 2 - Reading values into a list and removing duplicates (15 pts)
In this program you should implement two functions. The first, called
`read_list()` , asks the user for a series of integers until the user enters 0 to stop. The
integers entered by the user (not including the final 0) should be stored in a list that the
function should then return. Here is a sample run of the user entering values (user’s inputs
are in italics) and what the function should return (internally) in the program:

```
Enter value (0 to stop): 5
Enter value (0 to stop): 3
Enter value (0 to stop): 6
Enter value (0 to stop): 2
Enter value (0 to stop): 7
Enter value (0 to stop): 6
Enter value (0 to stop): 3
Enter value (0 to stop): 3
Enter value (0 to stop): 0
```

If the user entered the values above, the function should return the list:
`[5, 3, 6, 2, 7, 6, 3, 3]`

The second function you should write is called
`remove_duplicates(num_list)` . This function is passed a list of integers
( `num_list` ) and it should create and return a new list which does not include any duplicate
values from the original list passed in. The original list passed into the function
( `num_list` ) should not be changed. For example, calling:

`remove_duplicates([5, 3, 6, 2, 7, 6, 3, 3])`

should return the following new list:

`[5, 3, 6, 2, 7]`

If your function is called with the empty list, as follows:

`remove_duplicates([])`

then it should return a new empty list:

`[]`
"""

# Define the function read_list here

def read_list():
    """
    This function should ask the user for a series of integer values
    (until the user enters 0 to stop) and store all those values in a
    list.  That list should then be returned by this function.
    """
    lst=[];
    while 1:
      print("Enter value (0 to stop):");
      a=int(input());
      if(a): lst.append(a);
      else: break;
    return lst;

# Define the function remove_duplicates here

def remove_duplicates(num_list):
    """
    This function is passed a list of integers and returns a new
    list with all duplicate values from the original list remove.
    """
    tmp=[];
    for i in range(len(num_list)):
      flag=1;
      for j in range(len(tmp)):
        if(num_list[i]==tmp[j]): flag=0;break;
      if(flag):tmp.append(num_list[i]);
    return tmp;

3# Test your function here

num_list = read_list()
print("Original list entered by user: ")
print(num_list)

no_duplicates = remove_duplicates(num_list)
print("List with duplicates removed: ")
print(no_duplicates)

"""## Question 3 - Zipping together two lists into a list of lists (10 pts)
In this program, implement the function `zip2lists(list1, list2)` . This
function is passed two lists of strings ( `list1` and `list2` ), where you can assume that both
lists both have the same length (number of elements). The function should return a new
list that "zips" together the two lists passed in. That is, the result should be a list that
contains lists that are pairs of elements, one from each of the original lists, in order. For
example, calling:

`zip2lists(['a', 'b', 'c'], ['d', 'e', 'f'])`

should return the following new list (of lists):

`[['a', 'd'], ['b', 'e'], ['c', 'f']]`

The original lists passed in should not be changed. If this function is passed two empty
lists, it should just return an empty list, since there would be no lists (of pairs) in the result.
In other words, calling:

`zip2lists([], [])`

should return the following empty list:

`[]`

You can think of that as a list that contains no lists as elements.
"""

# Define the function zip2lists here

def zip2lists(list1, list2):
    """
    This function is passed two lists of strings.  Both lists both have
    the same length.  The function returns a new list that "zips" together
    the two lists passed in into a list that contains lists that are pairs of
    elements, one from each of the original lists, in order.  For example, if
    this function were passed the lists ['a', 'b', 'c'] and ['d', 'e', 'f'] it
    would return the list of lists:
    [['a', 'd'], ['b', 'e'], ['c', 'f']]
    The original lists passed in should not be changed.
    Note that if this function is passed two empty lists, it should just
    return an empty list, since there would be no lists (of pairs) in the
    result.
    """
    result=[];
    for i in range(len(list1)):
      tmp=[];
      tmp.append(list1[i]);
      tmp.append(list2[i]);
      result.append(tmp);
    return result;

# Test your function here

result_list = zip2lists(['a', 'b', 'c'], ['d', 'e', 'f'])
print(result_list)      # should print [['a', 'd'], ['b', 'e'], ['c', 'f']]