# -*- coding: utf-8 -*-
"""William Li - G10 2021 Fall Homework 1 - Variables and Expressions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSdbUOC-HsLX18TII7w-3gZh3uq2nczE

# G10 2021 Fall Homework 1 - Variables and Expressions (50 pts)


---

## **Sectuib 0: Prerequisites**

### Prerequisite 0.1
Familiarize yourself with Google Colab, read the quick tutorial here: https://colab.research.google.com/notebooks/intro.ipynb#


**Now, you may start your Journey into the world of Python :)**

## **Section 1: Basic Knowledge (10 pts)**

### Question 1.1 - Print your name (5 pts)
Assign your First Name to a variable, and then print that on the screen.
"""

# Write your code here for Question 1.1

name="Zetong";
print(name);

"""### Question 1.2 - Modify your name (5 pts)
Modify the value of the previous variable into your Full Name, and then print that on the screen.
"""

# Write your code here for Question 1.2
name="Zetong Li";
print(name);

"""## **Section 2: Variables and Expressions (40 pts)**

### Question 2.1 - User name and age (10 pts)
Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year that they will turn 100 years old.
"""

# Write your code here for Question 2.1
print("Your name?");
name=input();
print("Your age?");
age=int(input());
year=2021+100-age;
print("Your will be 100 years old in",year,",",name,".");

"""### Question 2.2 - Dividing 2 integers and finding both quotient and remainder (10 pts)
In this part, you are asked to write a small program that
* Ask for user inputs of 2 `int` number
* Convert user inputs into `int` if necessary
* Calculate both the quotient and remainder
* Print out the result

Example: `num1 = 5` and `num2 = 2`
* Your program should print:

`The quotient is: 2`

`The remainder is: 1`
"""

# Write your code here for Question 2.2

##include<cstdio>
#int main()
#{
#    int a,b;
#    scanf("%d%d",&a,&b);
#    print("%d %d\n",a/b,a-b*(a/b));
#    return 0;
#}
a=int(input());
b=int(input());
print("The quotient is: ",int(a/b));
print("The remainder is: ",a-int(a/b)*b);

"""### Question 2.3 - Finding the volume of a sphere using Python (10 pts)
A sphere is a solid ball in the 3-dimensional space. The volume $V$ of a sphere is given by:

$V = \frac{4}{3} \pi r^3$

In this question, write a program that ask user to input the radius of the sphere `r` and calculate the Volume.
* Convert user inputs to `float`
* Take $\pi = 3.14$
"""

# Write your code here for Question 2.3
import math
from math import pow
pi=3.14;
r=(float(input()));
print(4/3*pi*pow(r,3));

"""### Question 2.4 - Write a program that asks the user for a temperature in Fahrenheit and prints out the same temperature in Celsius. (10 pts)

The relationship between Fahrenheit and Celsius is:
$$C = \dfrac{5}{9} (F-32)$$

In this question, write a program that ask user to input a temperature in Fahrenheit `f` and calculate the same temperature in Celsius. Print the result

You need to first write the program in Pseudocode and then convert it into real Python code
"""

# Write your code here for Question 2.4

'''
Pseudocode begin
#include<cstdio>
int main()
{
  int f;
  scanf("%d",&f);
  printf("%.4lf\n",double(5/9)*(f-32));
  return 0;
}
Pseudocode end
'''

f=float(input());
print(5/9*(f-32));