# -*- coding: utf-8 -*-
"""William Li - G10 2021 Fall Homework 2 - Control Flows.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1usxLjKQXU97Fj7Q84h8zYskG7EiAJBRV

# G10 2021 Fall Homework 2 - Control Flows (60 pts)


---

### Question 1 - Your First for-loop (10 pts)
Write a for loop to print 3 lines of "Hello"
"""

# Write your code here for Question 1

for i in range (3):
  print("Hello");

"""### Question 2 - Your Second for-loop (10 pts)
Write a program in the file liftoff.py that prints out the calls for a spaceship that is about to launch. Countdown the numbers from 10 to 1 and then write “Liftoff!” Your program should include a **for** loop using **range**. A sample run of the program is below.



```
10
9
8
7
6
5
4
3
2
1
Liftoff!
```


"""

# Write your code here for Question 2

for i in range (10,0,-1):
  print(i);
print("Liftoff");

"""### Question 3 - Your Third for-loop (10 pts)
Write a for loop to print all multiples of 7 from 1, 2, ..., 100
"""

# Write your code here for Question 3
for i in range (7,100,7):
  print(i);

"""### Question 4 - If statements (10 pts)
Write a program that:
* Ask the user to input an integer (you can assume that the user actually enters an integer)
* Check whether the integer is
    - positive
    - zero
    - negative
* Print the result back to the user
"""

# Write your code here for Question 4
a=int(input());
if(not a): print("zero");
elif (a>0): print("positive");
else: print("negative");

"""### Question 5 - Moon Weight (10 pts)
Humans first landed on the moon on July 20, 1969. People have often wondered how much they would weigh if they were on the moon. It turns out that on the moon, you would weigh **16.5%** of your weight on Earth.

Write a program that asks the user for their weight (you can assume is a real-valued input is given by the user) and prints out their weight on the moon. If the user enters a negative value (yes, they’re being mean and trying to break your program), you should just print out that weights can’t be negative. Remember when writing your solution, that it’s good programming style to use **constants** where appropriate. Two sample runs of the program are shown below (user input is in *italics*).

Sample run 1 (note the imprecision of floating-point numbers in the answer)

```
Enter your weight: 165.3
Your weight on the moon is 27.274500000000003
```

Sample run 2

```
Enter your weight: -13
Sorry, you can't have a negative weight.
```




"""

# Write your code here for Question 5
k=0.165;
print("Enter your weight: ",end="");
a=float(input());
if(a<=0): print("Sorry, you can't have a negative weight.");
else: print(a*k);

"""### Question 6 - Sentinel Loops (10 pts)
**Sentinel:** A value that signals the end of user input.

Write a program that prompts the user for numbers until users type -1, then output the total of the numbers.
In this case, -1 is the **sentinel value**.

Sample run 1

```
Type a number: 10
Type a number: 20
Type a number: 30
Type a number: -1
total is 60

```




"""

# Write your code here for Question 6
#cpp version
#include<cstdio>
#int main()
#{int a=0,ans=0;while(~scanf("%d",&a)) ans+=a;printf("%d\n",1+ans);return 0;}
ans=0
while 1:
  a=int(input());
  if(a+1):ans+=a;
  else:break;
print(ans);